conda/conda-concourse-ci

concourse-server/docker-compose.yml
conda_concourse_ci/bootstrap/config/build_platforms.d/example.yml
conda_concourse_ci/bootstrap/config/config.yml
conda_concourse_ci/bootstrap/config/uploads.d/anaconda-example.yml
conda_concourse_ci/bootstrap/config/uploads.d/custom-example.yml
conda_concourse_ci/bootstrap/plan_director.yml
conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
conda_concourse_ci/uploads.py
tests/data/config-test/config.yml
tests/data/config-test/uploads.d/custom-example.yml
tests/test_cli.py
tests/test_execute.py

This is a different workflow, where pipelines are always submitted by the c3i program.  The old way was that the initial pipeline was uploaded by the c3i program, but subsequent pipelines were uploaded by a resource.
By giving this to c3i, it is more feasible to have differently named pipelines for each github PR or commit.  This works towards #7 but does not completely implement everything needed there.

use c3i to submit execute pipelines, for unique names

---

conda_concourse_ci/execute.py
tests/test_execute.py

The hope is that this will allow the package resolving process to respect condarc.  It may also be faster due to caching on the conda-build side.

use conda-build's get_build_index function rather than conda's get_index

---

conda_concourse_ci/compute_build_graph.py
tests/test_compute_build_graph.py

even if they are not strictly necessary to build
Prior to this, even if you were building an upstream dependency in a batch, if that upstream dep was already available for installation, then the intradependency would not affect the build ordering and topology.

add intradependencies for builds within a batch

---

.travis.yml
conda_concourse_ci/compute_build_graph.py
tests/test_compute_build_graph.py

fixes errors like:
```
WARNING:/opt/miniconda/lib/python3.6/site-packages/conda_concourse_ci/compute_build_graph.py:Dependency perl, version >=5.20.3.1 is not installable from your channels: [] with subdir osx-64.  Seeing if we can build it...
Error: bad character '=' in package/version: >=5.20.3.1
```

refactor _buildable to better handle boolean expression specs

---

conda_concourse_ci/execute.py

Specifying rsync_opts explicitly overrides the default ones. In this case,
`--omit-dir-times` replaced `-Pav`, which caused no artifacts to be synced.
What we want, is a combination of both. Plus, since the source folder
could be a shared folder across multiple users, disable preservation of
permissions too.

Specify rsync options correctly

---

docker/Dockerfile

This is required for running tests which involve libraries
linking to libx11.so
cc @msarahan @mingwandroid

Make runtime deps of CDT pkgs part of the container

---

conda_concourse_ci/execute.py

for args to conda-build.  This lets us do things like run conda-build with linux32, and build 32-bit packages in the 64-bit docker containers.

add build prefix & suffix command parsing from .yml files

---

conda_concourse_ci/compute_build_graph.py
conda_concourse_ci/execute.py

If an output had the same name as the top-level recipe, collapsing subpackages was breaking.  This may have been due to recent conda-build changes, which changed the way that outputs are determined from the recipe.

fix identification of 'master' recipe for collapsing subpackages

---

.travis.yml
conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
conda_concourse_ci/utils.py
tests/test_cli.py

This allows you to save a default config dir to your condarc, like this:
```
conda_build:
matrix_base_dir: ~/code/automated-build/c3i_configurations/anaconda_public
```
And it'll by default use all configurations in that folder.  Now, if you want to restrict it, you can also add glob patterns at the CLI:
``c3i one-off mcs_test click-feedstock -p "linux*"``
will build only platforms whose filename starts with linux

allow storage of config dir; specify platform names with glob pattern

---

conda_concourse_ci/compute_build_graph.py
conda_concourse_ci/execute.py
tests/data/win_split_outputs_compiler_reduction/conda_build_config.yaml
tests/data/win_split_outputs_compiler_reduction/meta.yaml
tests/test_compute_build_graph.py
tests/test_execute.py

This relies on recent CB3 improvements to say what "used" variables are.  That code should only exist in CB3.  It also changes the package key from the collection of packages (which should ideally reflect variants) to the combination of package names with variants.  It's more direct and less error-prone.
CC @jjhelmus @nehaljwani

fix loss of variables due to unfinalized data omitting hash from keys

---

conda_concourse_ci/compute_build_graph.py

topological_sort(reverse=True) is removed

Workaround for newer networkx

---

docker/c3i-linux-ppc64le/Dockerfile

Some Python 3 command line utilities, including those which use click, require
that a unicode supporting locale be set.

set locale in ppc64le docker container

---

docker/c3i-linux-64/Dockerfile

Bumped into ``msgfmt`` missing when trying to build glib.  Ray recommends that gettext is so fundamental, it should be part of the image.

add gettext to docker image

---

conda_concourse_ci/compute_build_graph.py

Traversing in reverse orientation doesn't get the same result and can miss cycles.

Fix cycle output

---

conda_concourse_ci/cli.py
conda_concourse_ci/compute_build_graph.py
conda_concourse_ci/execute.py
tests/data/functools32-feedstock/recipe/meta.yaml
tests/data/intradependencies/uses_zlib/meta.yaml
tests/data/intradependencies/zlib/meta.yaml
tests/data/selector_run/meta.yaml
tests/test_cli.py
tests/test_compute_build_graph.py
tests/test_execute.py

This looks in your configured channels for existing builds, and skips them.  Maybe that will help with rebuild efforts.  It also enables using clobber and append files, with the current purpose being disabling noarch: python from conda-forge without recipe divergence.

skip existing; implement append/clobber files

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

@jjhelmus this is what you proposed a long time ago.  It lets us pass things like ``--python=3.7`` to limit our builds to specific python versions.

add pass-through to cb for args not recognized by c3i

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/data/batch_sample.txt
tests/test_cli.py
tests/test_execute.py

c3i batch can be used to submit a batch of one-off jobs which are submitted
only when the number of activate jobs is below a given threshold

add batch sub-command

---

conda_concourse_ci/compute_build_graph.py
conda_concourse_ci/execute.py
setup.cfg

My initial way to do this was wrong.  Sourceclear needs the build-time dependencies, not the run-time dependencies.  This uses a new conda-build feature to accomplish that.

use conda-debug (to be released in conda-build 3.17.0)

---

conda_concourse_ci/execute.py

We've seen some dumb stuff happen when the index files generated during build end up being copied over into our actual package collection.  This change should limit the stuff being present in any rsync to just packages.

filter more stuff from rsync intermediaries (index output)

---

conda_concourse_ci/execute.py

Join prefix and suffix commands using "&& ", do not use a trailing space.
In some scriping languages, such as batch, a trailing space can change the
behavior of a command.  The particular cases where this was observed was in the
command "set TEMP=%CD%".  When joined with a trailing space the space was added
to the TEMP variable.
See: https://superuser.com/questions/57723

no trailing space when joining prefix/suffix cmds

---

conda_concourse_ci/bootstrap/config/config.yml
conda_concourse_ci/execute.py
tests/data/config-test/config.yml
tests/data/linux-config-test/config.yml

As per https://github.com/pivotalservices/concourse-pipeline-samples/tree/master/concourse-pipeline-patterns/vault-integration you can update jobs to use vault by just changing variables in the config file.
Since the intermediate-private-key is used elsewhere in c3i, it needs to stay in the variables config file for now. But, with this change the key won't be uploaded every time.
Example part of a build:
```
groups: []
resources:
- name: rsync-recipes
type: rsync-resource
source:
base_dir: /ci/imagesize-feedstock/plan_and_recipes
disable_version_path: true
private_key: ((common.intermediate-private-key))
server: bremen.corp.continuum.io
user: ci
```
related to https://github.com/ContinuumIO/automated-build/pull/11

Use intermediate key from vault

---

conda_concourse_ci/execute.py

Sourceclean failures should not fail the entire job

sourceclear failures are allowed

---

conda_concourse_ci/execute.py

Writing to the _netrc file can create a race condition if multiple builds are
scheduled on the same worker. Failing to write this file should not fail the
build although will result in private repositories not being accessable.

do not fail job if _netrc is not written

---

conda_concourse_ci/execute.py

This has been tested and gives good results.
For reference:
"cmd1 || cmd2" will execute cmd2 if cmd1 has a non-zero errorlevel
"cmd1 && cmd2" will execute cmd2 if cmd1 has a zero errorlevel
"cmd1 & cmd2" will always xecute cmd2
Commands submitted to concourse are joined with &&. Grouping the netrc
writing commands and exit 0 with () is needed for the || to have its intended
effect.

Another _netrc writing fix on Windows

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/data/config-test/build_platforms.d/centos5-64.yml
tests/data/config-test/build_platforms.d/osx109.yml
tests/data/config-test/build_platforms.d/win64.yml
tests/data/config-test/config.yml
tests/test_cli.py
tests/test_execute.py
tests/utils.py

Use a pool of locks backed by a Git repository to limit the number of concurrent build tasks run on each build platform.  Once all locks are acquired additional jobs will wait until a lock in the appropriate pool becomes available and will then start.  By default a delay of 10 seconds is used before retrying to acquire a lock although this can be controlled by the `retry_delay` parameter of the lock resource.
Locks are acquired immediately before the build step and released regardless of the success of the build step. 
Locks are only used for the `one-off` sub-command when the `--use_lock_pool` argument is included.
This implementation requires the following additions to the concourse configuration files:
* each build worker configuration needs to include a `pool_name` entry which …

Use a pool of locks to limit the number of concurrent build on each platform

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

c3i batch does not check the number of outstanding jobs if
the --use_lock_pool argument is passed as the pool resource is used to
limit concurrent jobs.

c3i batch accepts --use_lock_pool

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

Add the --use-repo-access argument to the one-off and batch subcommands.
This argument conditionally enables the repo access credentials
(username and token) to be passed to the build jobs. By default these
are not passed.
Writing the _netrc/.netrc can stall workers if another job is accessing or
writing the file at the same time. This effects windows especially. The
argument will not write these files unless they are specifically
required and requested by the user.

add --use-repo-access arg to one-off and batch

---

conda_concourse_ci/execute.py

Do not error out when the overlinking check fails on Windows. Currently
conda-build's overlinking check is case-sensitive on Windows which
causes numerous false positives.
This should be re-enabled once conda-build has better overlinking check
behavior on Windows.

overlinking check does not error on windows

---

.travis.yml
conda_concourse_ci/compute_build_graph.py

Allow the submission of recipe which have outputs which dependent on
each other. All dependencies with a name that matches one of the outputs
of the recipe is ignored when examining the intradependencies of the
submission.

allow submission of recipe dependent outputs

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py

This is really messy and absolutely needs to be cleaned up. 
It adds a flag, `--automated-pipeline`, to the one-off command that will change the pipeline to pull the recipe from github. It will then have a gated task that will only get ran when the master branch's meta.yaml gets updated. 
Right now that task does nothing, we should update this to make it do something more useful. Maybe it moves these packages to some staging area.

Automated pipeline flag

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

This PR adds the `--branches` flag. 
Using this flag you can either specify exactly one or n number of branches where n is equal to the number of feedstocks passed in.
If you do not pass in a branch it will default to the `automated-build` branch.
This still needs to figure out how to pull all of the correct things into the build tasks.

add branches flag

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

Add an optional "stage_for_upload" jobs to pipelines which executes the
task defined in the stage_for_upload_config section of the configuration
with the artifact directory passes in via the ARTIFACT_DIR environment
variable. This job is created when the --stage-for-upload option is
specified on the command line.
Additionally, adds a --commit-msg command line option where a git commit
message can be specified that is passed to the the upload job via the
GIT_COMMIT_MSG environment variable.

add optional stage_for_upload job

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

Add a command line option to add a job to the concourse pipeline
responsible for pushing a named branch to master. The actual logic for
the push is defined in the push-branch-config section of the
configuration file.
Example usage:
c3i one-off prefix_sphinx --automated-pipeline --branches test --push-branch --stage-for-upload --commit-msg "sphinx 3.0.4" sphinx-feedstock

cli option to add push-branch job

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

Trigger the stage_for_upload and push_branch_... jobs when the file
specified in the --pr-file command line option appears in the git
repository specified in the pr-repo configuration option. The
expectation is that when this file appears when the PR for the
particular pipeline is merged.

trigger upload and branch push via PR merge

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_cli.py

This adds the --destroy-pipeline flag. It must be used along side the --push-branch and --stage-for-upload flags.
When the --destroy-pipeline flag is passed, the pipeline will be torn down after the artifacts are staged for upload and the recipe repo is updated.

destroy pipeline flag

---

conda_concourse_ci/concourse_config.py
conda_concourse_ci/execute.py

Use the `conda_build_config.yaml` files from the rsync_recipe resource to build the appropriate package from the pipeline in automated pipelines.

Use conda_build_config.yaml from rendered recipes in automated pipelines

---

conda_concourse_ci/concourse_config.py
conda_concourse_ci/execute.py

Repo access is needed when conda-build is run, therefore those commands
must be run before the build commands (but after the prefix commands)

make repo access cmds go before build cmds

---

conda_concourse_ci/execute.py

This fixes win-32 testing and also points at the .tar.bz2 for testing instead of the recipe which was deprecated in conda-build 3.16.0

point at package for testing

---

ci/pack-build-env.yaml
conda_concourse_ci/bootstrap/config/build_platforms.d/example.yml
conda_concourse_ci/bootstrap/config/test_platforms.d/example.yml
conda_concourse_ci/bootstrap/plan_director.yml
docker/build_job.yml
tests/data/config-test/build_platforms.d/centos5-64.yml
tests/data/linux-config-test/build_platforms.d/centos5-64.yml
tests/data/plan_director.yml

In order to fix dockerhub's request for more money based on our usage,
we want to reduce that usage. This is an attempt to do that by checking
only every 1 hour.
* Fixes inconsistent indentation on one source block
* Adds `check_every: 1h` to all docker-image resources

Set check_every to 1 hour on docker-image

---

conda_concourse_ci/bootstrap/plan_director.yml
conda_concourse_ci/concourse_config.py
conda_concourse_ci/uploads.py
docker/build_job.yml

Moving the package building images back to ECR now that a non-manifest list exists.
Tested these changes on the following feedstocks:
- botocore-feedstock (noarch)
- curl-feedstock

Using new ECR build image.
