conda/conda-concourse-ci

.travis.yml
conda_concourse_ci/compute_build_graph.py
conda_concourse_ci/execute.py
docker/Dockerfile
tests/conftest.py
tests/test_compute_build_graph.py
tests/test_execute.py

This may require a CB 3.0.1 release to actually work

fix output paths and tweak tests for CB 3.0.0

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py

@nehaljwani I hope this fixes the "disappearing file" problem you were seeing.  That was a race condition, I believe.

omit json files from rsync of artifacts and source

---

conda_concourse_ci/execute.py

See what you think @msarahan, it means I don't have to do a load of editing.

Also make output_order_recipes_ file

---

conda_concourse_ci/compute_build_graph.py
tests/test_compute_build_graph.py

Option for finalize=True

---

conda_concourse_ci/execute.py

xref: https://github.com/ContinuumIO/automated-build/pull/3

Add support for linux-ppc64le worker

---

docker/c3i-linux-ppc64le/Dockerfile
docker/c3i-linux-ppc64le/install_miniconda.sh

I shifted the 'pings' to keep the VPN tunnel alive to the ssh config in the startup script instead.

Add Dockerfile for c3i-linux-ppc64le

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py

add c3i rm command to make pipeline cleanup faster

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py

allow wildcards in c3i rm

---

conda_concourse_ci/execute.py

add --error-overlinking flag to error out when deps need fixing

---

docker/c3i-linux-64/Dockerfile

xref: https://github.com/ContinuumIO/anaconda-issues/issues/9270

conda/c3i-linux-64: add more X libs

---

conda_concourse_ci/compute_build_graph.py

I saw this broken behavior when trying to build icu and boost in one go.  In the old logic, the dep from the libboost subpackage to icu was not being transferred to the top-level boost recipe.  When the subnode was removed, all the dependency info between icu and libboost was lost.

fix subpackages depending on earlier builds losing their edges

---

docker/c3i-linux-64/Dockerfile

Add libXScrnSaver to conda/c3i-linux-64

---

conda_concourse_ci/execute.py
tests/test_execute.py

This is required for cloning private repositories on Github

Use ~/.netrc for storing github credentials

---

conda_concourse_ci/compute_build_graph.py

depends on https://github.com/conda/conda-build/pull/3051

ignore local packages when checking is_package_built

---

.gitignore
conda_concourse_ci/compute_build_graph.py
conda_concourse_ci/execute.py

Ties in with https://github.com/conda/conda-build/pull/3123

Record recipe history

---

conda_concourse_ci/cli.py
conda_concourse_ci/compute_build_graph.py
conda_concourse_ci/execute.py
tests/test_cli.py

This requires a token, which has been added to the private automated build repo.

implement sourceclear scan integration

---

docker/c3i-linux-64/Dockerfile

(Not my wife, she does not have much time for geeky stuff).

We need PAM system libs for pamela

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_execute.py

c3i trigger : Can be used to re-trigger (failed?) pipelines
c3i abort   : Can be used to abort running builds without nuking the pipeline

Introducing ... c3i trigger & c3i abort

---

conda_concourse_ci/execute.py

goes with https://github.com/ContinuumIO/automated-build/pull/24

replace packed env with standalone conda for win/mac

---

conda_concourse_ci/execute.py

This removes all of the other feedstock files except for recipe.

remove everything except for the recipe

---

conda_concourse_ci/execute.py

When triggered from the pr-merged resource, run the the stage_for_upload job
prior to push_branch_to_<package>-feedstock jobs. This avoids a race
condition between these jobs where the artifacts are deleted prior to
staging if the push_branch_... jobs are run first.

stage packages for upload before branch push

---

conda_concourse_ci/execute.py

Adds the logic to write a PR number to a file in the pipeline directory

write pr number to file

---

conda_concourse_ci/execute.py

Skip triggering special jobs and fix an error

fix error and skip certain jobs

---

ci/pack-build-env.yaml
conda_concourse_ci/concourse_config.py
conda_concourse_ci/execute.py

A few fixes, important Windows worker fix for preventing autorun batch scripts

---

conda_concourse_ci/cli.py
conda_concourse_ci/concourse.py
conda_concourse_ci/execute.py

This adds pause and unpause to c3i. The main benefit here is the use of wildcards.

add pause and unpause

---

ci/pack-build-env.yaml
conda_concourse_ci/bootstrap/config/build_platforms.d/example.yml
conda_concourse_ci/bootstrap/config/test_platforms.d/example.yml
conda_concourse_ci/bootstrap/plan_director.yml
conda_concourse_ci/concourse.py
conda_concourse_ci/concourse_config.py
conda_concourse_ci/execute.py
conda_concourse_ci/uploads.py
docker/build_job.yml
tests/data/config-test/build_platforms.d/centos5-64.yml
tests/data/linux-config-test/build_platforms.d/centos5-64.yml
tests/data/plan_director.yml

this adds auth to the docker calls so we can avoid hitting the api rate limit.

Docker auth

---

conda_concourse_ci/cli.py
conda_concourse_ci/execute.py
tests/test_uploads.py

This adds a flag that will only remove pipelines older than the defined days

Reap older

---

conda_concourse_ci/execute.py

Fixed the execute.py to check for "none" type

Fixed check for none type

---

ci/pack-build-env.yaml
conda_concourse_ci/bootstrap/plan_director.yml
conda_concourse_ci/concourse_config.py
conda_concourse_ci/uploads.py
docker/build_job.yml

Signed-off-by: Connor Martin <connormartin7@gmail.com>

Migrate to ECR
